import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import { getAuth, GoogleAuthProvider, signInWithPopup, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import { getFirestore, collection, doc, addDoc, updateDoc, deleteDoc, onSnapshot, serverTimestamp, writeBatch } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";

const APP_VERSION="3.1.0";
const LOCAL_STORAGE_KEY="freezer_inventory_app_data";
const MIGRATION_DISMISSED_KEY="furikore_migration_dismissed_v2";
const FIRESTORE_PATH=["households","default","areas","freezer","items"];
const CATEGORIES=["鶏肉","豚肉","牛肉","加工肉","魚介類","野菜","主食","冷凍食品","アイス","お菓子","調味料","作り置き","その他"];

const firebaseConfig={apiKey:"AIzaSyCo76wuPHhxCd3NH_qGoQxplxhVLNhrYsQ",authDomain:"furikore-395e8.firebaseapp.com",projectId:"furikore-395e8",storageBucket:"furikore-395e8.firebasestorage.app",messagingSenderId:"608348115093",appId:"1:608348115093:web:84623fa7dd36cd5e94cb9c"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider(),itemsRef=collection(db,...FIRESTORE_PATH);
let items=[],unsubscribeItems=null,mode="display",selectedItemId=null;
const $=id=>document.getElementById(id);
const els={authStatus:$("authStatus"),loginBtn:$("loginBtn"),logoutBtn:$("logoutBtn"),mainApp:$("mainApp"),itemCount:$("itemCount"),syncStatus:$("syncStatus"),migrationCard:$("migrationCard"),migrateBtn:$("migrateBtn"),dismissMigrationBtn:$("dismissMigrationBtn"),displayTab:$("displayTab"),editTab:$("editTab"),addTab:$("addTab"),displayPanel:$("displayPanel"),editPanel:$("editPanel"),addPanel:$("addPanel"),displaySearch:$("displaySearch"),displayCategory:$("displayCategory"),displaySort:$("displaySort"),displayList:$("displayList"),editEmpty:$("editEmpty"),editCard:$("editCard"),editTitle:$("editTitle"),editForm:$("editForm"),editId:$("editId"),editName:$("editName"),editCategory:$("editCategory"),editQuantity:$("editQuantity"),editUnit:$("editUnit"),editFrozenDate:$("editFrozenDate"),editLocation:$("editLocation"),editMemo:$("editMemo"),editDecOne:$("editDecOne"),editDecQuarter:$("editDecQuarter"),editIncQuarter:$("editIncQuarter"),editIncOne:$("editIncOne"),backToDisplayBtn:$("backToDisplayBtn"),deleteEditBtn:$("deleteEditBtn"),addForm:$("addForm"),addName:$("addName"),addCategory:$("addCategory"),addQuantity:$("addQuantity"),addUnit:$("addUnit"),addFrozenDate:$("addFrozenDate"),addLocation:$("addLocation"),addMemo:$("addMemo"),recentList:$("recentList"),exportBtn:$("exportBtn"),importInput:$("importInput")};

function todayIso(){return new Date().toISOString().slice(0,10)}
function daysSince(s){if(!s)return null;const d=new Date(`${s}T00:00:00`);if(Number.isNaN(d.getTime()))return null;const n=new Date(),t=new Date(n.getFullYear(),n.getMonth(),n.getDate());return Math.floor((t-d)/86400000)}
function roundQty(v){return Math.round((Number(v)||0)*4)/4}
function formatQty(v){const n=roundQty(v);return Number.isInteger(n)?String(n):String(n).replace(/\.?0+$/,"")}
function normalizeCategory(c){const map={肉:"鶏肉",魚:"魚介類"};return map[c]||(CATEGORIES.includes(c)?c:"その他")}
function normalizeItem(raw={}){return{name:String(raw.name||raw.itemName||raw.title||"").trim(),category:normalizeCategory(raw.category||"その他"),quantity:roundQty(raw.quantity??raw.amount??raw.count??1),unit:raw.unit||"個",frozenDate:raw.frozenDate||raw.date||raw.freezingDate||todayIso(),location:raw.location||raw.place||"未設定",memo:raw.memo||raw.note||"",schemaVersion:2}}
function ageClass(age){if(age===null)return"fresh";if(age>=61)return"very-old";if(age>=31)return"old";if(age>=15)return"watch";return"fresh"}
function ageLabel(age){return age===null?"日付未設定":`${age}日`}
function escapeHtml(str){return String(str).replace(/[&<>"']/g,s=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[s]))}
function getSelectedItem(){return items.find(x=>x.id===selectedItemId)||null}

function switchMode(next){mode=next;els.displayPanel.classList.toggle("hidden",mode!=="display");els.editPanel.classList.toggle("hidden",mode!=="edit");els.addPanel.classList.toggle("hidden",mode!=="add");els.displayTab.classList.toggle("active",mode==="display");els.editTab.classList.toggle("active",mode==="edit");els.addTab.classList.toggle("active",mode==="add");render()}
function getDisplayItems(){const q=els.displaySearch.value.trim().toLowerCase(),cat=els.displayCategory.value,sort=els.displaySort.value;return items.filter(item=>{const hay=`${item.name} ${item.category} ${item.location} ${item.memo}`.toLowerCase();return(!q||hay.includes(q))&&(cat==="all"||item.category===cat)}).sort((a,b)=>{const da=daysSince(a.frozenDate)??-1,db=daysSince(b.frozenDate)??-1;if(sort==="ageAsc"){if(da!==db)return da-db}else if(sort==="category")return`${a.category}${a.name}`.localeCompare(`${b.category}${b.name}`,"ja");else if(sort==="name")return a.name.localeCompare(b.name,"ja");else if(sort==="quantityDesc"){if(Number(b.quantity)!==Number(a.quantity))return Number(b.quantity)-Number(a.quantity)}else if(sort==="quantityAsc"){if(Number(a.quantity)!==Number(b.quantity))return Number(a.quantity)-Number(b.quantity)}else{if(db!==da)return db-da}return a.name.localeCompare(b.name,"ja")})}
function render(){els.itemCount.textContent=`${items.length}件`;renderDisplayList();renderEditPanel();renderRecent()}

function renderDisplayList(){const list=getDisplayItems();els.displayList.innerHTML="";if(!list.length){els.displayList.innerHTML='<div class="card empty">在庫がありません。新規追加タブから登録しましょう。</div>';return}const groups={};for(const item of list){const cat=item.category||"その他";if(!groups[cat])groups[cat]=[];groups[cat].push(item)}for(const cat of CATEGORIES){if(!groups[cat]?.length)continue;const section=document.createElement("section");section.className="category-block";section.innerHTML=`<div class="category-title">${escapeHtml(cat)}</div>`;groups[cat].forEach(item=>{const age=daysSince(item.frozenDate),cls=ageClass(age),row=document.createElement("button");row.type="button";row.className="inventory-row";row.innerHTML=`<span class="row-name">${escapeHtml(item.name||"名称未設定")}</span><span class="row-qty">${formatQty(item.quantity)}${escapeHtml(item.unit||"個")}</span><span class="row-age ${cls==="fresh"?"":cls}">${ageLabel(age)}</span>`;row.addEventListener("click",()=>startEdit(item));section.appendChild(row)});els.displayList.appendChild(section)}}
function renderEditPanel(){const item=getSelectedItem();els.editEmpty.classList.toggle("hidden",!!item);els.editCard.classList.toggle("hidden",!item);if(!item)return;if(els.editId.value!==item.id)fillEditForm(item)}
function fillEditForm(item){els.editId.value=item.id;els.editTitle.textContent=item.name||"在庫を編集";els.editName.value=item.name||"";els.editCategory.value=item.category||"その他";els.editQuantity.value=formatQty(item.quantity);els.editUnit.value=item.unit||"個";els.editFrozenDate.value=item.frozenDate||todayIso();els.editLocation.value=item.location||"未設定";els.editMemo.value=item.memo||""}
function getEditPayload(){return normalizeItem({name:els.editName.value,category:els.editCategory.value,quantity:els.editQuantity.value,unit:els.editUnit.value,frozenDate:els.editFrozenDate.value,location:els.editLocation.value,memo:els.editMemo.value})}
function getAddPayload(){return normalizeItem({name:els.addName.value,category:els.addCategory.value,quantity:els.addQuantity.value,unit:els.addUnit.value,frozenDate:els.addFrozenDate.value,location:els.addLocation.value,memo:els.addMemo.value})}
function startEdit(item){selectedItemId=item.id;fillEditForm(item);switchMode("edit");window.scrollTo({top:0,behavior:"smooth"})}
function adjustEditQuantity(delta){const next=Math.max(0,roundQty(Number(els.editQuantity.value||0)+delta));els.editQuantity.value=formatQty(next)}
async function saveEdit(e){e.preventDefault();const id=els.editId.value;if(!id)return;const payload=getEditPayload();if(!payload.name)return;await updateDoc(doc(db,...FIRESTORE_PATH,id),{...payload,updatedAt:serverTimestamp()});selectedItemId=null;switchMode("display")}
async function deleteSelected(){const item=getSelectedItem();if(!item)return;if(!confirm(`${item.name}を削除しますか？`))return;await deleteDoc(doc(db,...FIRESTORE_PATH,item.id));selectedItemId=null;switchMode("display")}
function resetAddForm(){els.addForm.reset();els.addQuantity.value="1";els.addFrozenDate.value=todayIso();els.addCategory.value="鶏肉";els.addLocation.value="未設定"}
async function saveAdd(e){e.preventDefault();const payload=getAddPayload();if(!payload.name)return;await addDoc(itemsRef,{...payload,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});resetAddForm();switchMode("display")}

function getRecentTemplates(){const map=new Map(),sorted=[...items].filter(i=>i.name).sort((a,b)=>(b.createdAt?.seconds||b.updatedAt?.seconds||0)-(a.createdAt?.seconds||a.updatedAt?.seconds||0));for(const i of sorted){const key=`${i.name}|${i.category}|${i.unit}`;if(!map.has(key))map.set(key,i);if(map.size>=6)break}return[...map.values()]}
function renderRecent(){els.recentList.innerHTML="";const recent=getRecentTemplates();if(!recent.length){els.recentList.innerHTML='<p class="muted">登録後によく使う候補が表示されます。</p>';return}recent.forEach(item=>{const b=document.createElement("button");b.type="button";b.className="recent-chip";b.textContent=item.name;b.addEventListener("click",()=>{resetAddForm();els.addName.value=item.name;els.addCategory.value=item.category;els.addQuantity.value="1";els.addUnit.value=item.unit||"個";els.addLocation.value=item.location||"未設定";els.addMemo.value=item.memo||"";els.addFrozenDate.value=todayIso();switchMode("add");window.scrollTo({top:0,behavior:"smooth"})});els.recentList.appendChild(b)})}

function readLocalData(){try{const raw=localStorage.getItem(LOCAL_STORAGE_KEY);if(!raw)return[];const p=JSON.parse(raw);if(Array.isArray(p))return p.map(normalizeItem).filter(x=>x.name);if(Array.isArray(p.items))return p.items.map(normalizeItem).filter(x=>x.name);return[]}catch{return[]}}
function showMigrationIfNeeded(){const local=readLocalData(),dismissed=localStorage.getItem(MIGRATION_DISMISSED_KEY)==="1";els.migrationCard.classList.toggle("hidden",!(local.length&&!dismissed))}
async function migrateLocalData(){const local=readLocalData();if(!local.length)return;if(!confirm(`${local.length}件をFirebaseへコピーします。実行しますか？`))return;const batch=writeBatch(db);for(const item of local){const ref=doc(itemsRef);batch.set(ref,{...item,migratedFromLocal:true,createdAt:serverTimestamp(),updatedAt:serverTimestamp()})}await batch.commit();localStorage.setItem(MIGRATION_DISMISSED_KEY,"1");els.migrationCard.classList.add("hidden")}
function exportJson(){const data={app:"furikore",appVersion:APP_VERSION,exportedAt:new Date().toISOString(),schemaVersion:2,items:items.map(({id,...rest})=>rest)},blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`furikore_backup_${todayIso()}.json`;a.click();URL.revokeObjectURL(url)}
async function importJson(file){if(!file)return;const text=await file.text(),parsed=JSON.parse(text),arr=Array.isArray(parsed)?parsed:parsed.items;if(!Array.isArray(arr)){alert("読み込める在庫データが見つかりませんでした。");return}if(!confirm(`${arr.length}件をFirebaseへ追加します。よろしいですか？`))return;const batch=writeBatch(db);arr.map(normalizeItem).filter(x=>x.name).forEach(item=>{const ref=doc(itemsRef);batch.set(ref,{...item,importedAt:serverTimestamp(),createdAt:serverTimestamp(),updatedAt:serverTimestamp()})});await batch.commit();els.importInput.value=""}

function subscribeItems(){if(unsubscribeItems)unsubscribeItems();els.syncStatus.textContent="同期中";unsubscribeItems=onSnapshot(itemsRef,snap=>{items=snap.docs.map(d=>{const raw=d.data();return{id:d.id,...normalizeItem(raw),createdAt:raw.createdAt,updatedAt:raw.updatedAt}});if(selectedItemId&&!items.some(x=>x.id===selectedItemId))selectedItemId=null;els.syncStatus.textContent="同期済み";render()},err=>{console.error(err);els.syncStatus.textContent="同期エラー";alert("Firestoreの読み込みに失敗しました。")})}
function setupEvents(){els.loginBtn.addEventListener("click",()=>signInWithPopup(auth,provider));els.logoutBtn.addEventListener("click",()=>signOut(auth));els.displayTab.addEventListener("click",()=>switchMode("display"));els.editTab.addEventListener("click",()=>switchMode("edit"));els.addTab.addEventListener("click",()=>{resetAddForm();switchMode("add")});els.displaySearch.addEventListener("input",render);els.displayCategory.addEventListener("change",render);els.displaySort.addEventListener("change",render);els.editDecOne.addEventListener("click",()=>adjustEditQuantity(-1));els.editDecQuarter.addEventListener("click",()=>adjustEditQuantity(-0.25));els.editIncQuarter.addEventListener("click",()=>adjustEditQuantity(0.25));els.editIncOne.addEventListener("click",()=>adjustEditQuantity(1));els.editForm.addEventListener("submit",saveEdit);els.backToDisplayBtn.addEventListener("click",()=>switchMode("display"));els.deleteEditBtn.addEventListener("click",deleteSelected);els.addForm.addEventListener("submit",saveAdd);els.migrateBtn.addEventListener("click",migrateLocalData);els.dismissMigrationBtn.addEventListener("click",()=>{localStorage.setItem(MIGRATION_DISMISSED_KEY,"1");els.migrationCard.classList.add("hidden")});els.exportBtn.addEventListener("click",exportJson);els.importInput.addEventListener("change",e=>importJson(e.target.files?.[0]))}
onAuthStateChanged(auth,user=>{if(user){els.authStatus.textContent=`${user.email} でログイン中`;els.loginBtn.classList.add("hidden");els.logoutBtn.classList.remove("hidden");els.mainApp.classList.remove("hidden");resetAddForm();showMigrationIfNeeded();subscribeItems()}else{els.authStatus.textContent="Googleアカウントでログインすると、夫婦で同じ在庫を共有できます。";els.loginBtn.classList.remove("hidden");els.logoutBtn.classList.add("hidden");els.mainApp.classList.add("hidden");if(unsubscribeItems)unsubscribeItems();items=[]}});
setupEvents();
